apiVersion: v1
kind: Ingress
metadata:
  name: k8-ingress
spec:  
  rules:
  - host: localhost
  - http:
      paths:
      - backend:
          service:
            name: k8-fronend-cluster-service
            port:
              number: 6001