apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-dotnetapps
  namespace: ns-dotnetapps
spec:
  destination:    
    namespace: ns-dotnetapps
    server: 'https://kubernetes.default.svc'
  source:
    path: K8_SampleAspNetCore_Mvc_App/aksconfig
    repoURL: 'https://github.com/HMPTech/k8'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true