apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-dotnetapps
  namespace: argocd
spec:
  destination:    
    server: 'https://kubernetes.default.svc'
    namespace: ns-dotnetapps
  source:
    path: K8_SampleAspNetCore_Mvc_App/aksconfig
    repoURL: 'https://github.com/HMPTech/k8'
    targetRevision: master
  project: default
  syncPolicy:    
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

