apiVersion: v1
kind: Service
metadata:
  name: k8-lb-service
spec:
  selector:
    app: k8-sampleaspnetcore-mvc-app
  ports:
    - port: 6002
      targetPort: 5002
      nodePort: 30010
  type: LoadBalancer